inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.5.0

# Ignore 'Missing top-level class documentation comment.'
Style/Documentation:
  Enabled: false

# Allow Japanese comment.
Style/AsciiComments:
  Enabled: false

# Ignore 'Missing magic comment # frozen_string_literal: true.'
Style/FrozenStringLiteralComment:
  Enabled: false