version: "3"
services:

  web:
    build: .
    env_file: .env
    environment:
      DATABASE_HOST: db
      DOCKER_HOST_IP:
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
    depends_on:
      - db
  db:
    image: postgres:9.4-alpine
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"

volumes:
  db-data: